version: "3.9"
services:
  postgrest_server:
    env_file:
      - env/env.postgrest.development
    image: postgrest/postgrest
    ports:
      - "3000:3000"
    networks:
      - postgrest-backend
    depends_on:
      - postgresql_database
  postgresql_database:
    env_file:
      - env/env.postgres.development
    build:
      context: .
      dockerfile: .dockerfile
    ports:
      - "5433:5432"
    networks:
      - postgrest-backend
  swagger:
    image: swaggerapi/swagger-ui
    ports:
      - "8181:8080"
    expose:
      - "8181"
    environment:
      API_URL: http://localhost:3000/
    networks:
      - postgrest-backend

networks:
  postgrest-backend:
    driver: bridge